### ISSUE TITLE
mplayer doesn't update because mencoder is a dependencies of gnome-mplayer

### ISSUE THREAD

**Issue by ndias** [UnitedRPMs/mplayer#2]
After the last update of mplayer-1.3.0-4.fc24 in the repo the mencoder is still in version 1.3.0-3.fc24, this is a problem because mencoder is a dependencie of gnome-mplayer, so I can't update to the last version of mplayer.

**Comment by paulcarroty** [comment]
Thx for report, @ndias 

It's now fixed, you need to clean cache with `# dnf clean all`.
